version: 2
jobs:

  test:
    working_directory: ~/repo
    docker:
    - image: circleci/node:11.4.0
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Dependencies install
        command: yarn install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        name: Test
        command: yarn test

workflows:
  version: 2
  workflow:
    jobs:
    - test